if(NOT DEFINED LOVE_RUNTIME_SOURCE_DIR)
	message(FATAL_ERROR "LOVE_RUNTIME_SOURCE_DIR is required")
endif()

if(NOT DEFINED LOVE_RUNTIME_PACKAGE_DIR)
	message(FATAL_ERROR "LOVE_RUNTIME_PACKAGE_DIR is required")
endif()

file(GLOB LOVE_RUNTIME_FILES
	"${LOVE_RUNTIME_SOURCE_DIR}/*.exe"
	"${LOVE_RUNTIME_SOURCE_DIR}/*.dll")

if(NOT LOVE_RUNTIME_FILES)
	message(FATAL_ERROR "No LOVE runtime files found in ${LOVE_RUNTIME_SOURCE_DIR}")
endif()

file(MAKE_DIRECTORY "${LOVE_RUNTIME_PACKAGE_DIR}")
file(COPY ${LOVE_RUNTIME_FILES} DESTINATION "${LOVE_RUNTIME_PACKAGE_DIR}")

message(STATUS "Packaged LOVE runtime files in ${LOVE_RUNTIME_PACKAGE_DIR}")
